package db

// recipeCatalog 内置 ≥30 道，含需求点名的西红柿炒鸡蛋、酸菜鱼。
// 每道菜的食材名必须能在 ingredientCatalog / 别名表里解析到，
// 否则 Seed 会在启动期失败而不是带着空用料上线。
// 步骤写成家常口语，前端菜谱卡会展示前几味用料。
var recipeCatalog = []recDef{
	{
		Name: "西红柿炒鸡蛋", Tag: "家常", Servings: 2,
		Steps: []string{"鸡蛋加少许盐打散", "西红柿在顶部划十字，开水烫后去皮切滚刀块", "热锅凉油，倒入蛋液炒至刚凝固盛出", "留底油炒西红柿至出汁", "倒回鸡蛋，加糖提鲜，翻匀出锅"},
		Items: []recItemDef{
			{Name: "鸡蛋", Qty: 3, Unit: "个"},
			{Name: "西红柿", Qty: 2, Unit: "个"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "白糖", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
			{Name: "葱", Qty: 1, Unit: "根", Opt: true},
		},
	},
	{
		Name: "酸菜鱼", Tag: "川菜", Servings: 3,
		Steps: []string{"鱼片加盐、料酒、淀粉、蛋清抓匀上浆", "酸菜切段，泡椒拍裂", "热油爆花椒、干辣椒、姜蒜", "下酸菜煸出酸香，加水大火烧开", "鱼片散开下锅，刚变白即关火", "撒香菜，浇热油激发香气"},
		Items: []recItemDef{
			{Name: "酸菜鱼片", Qty: 400, Unit: "g"},
			{Name: "酸菜", Qty: 250, Unit: "g"},
			{Name: "泡椒", Qty: 30, Unit: "g"},
			{Name: "花椒", Qty: 8, Unit: "g"},
			{Name: "干辣椒", Qty: 8, Unit: "个"},
			{Name: "姜", Qty: 15, Unit: "g"},
			{Name: "蒜", Qty: 4, Unit: "瓣"},
			{Name: "香菜", Qty: 1, Unit: "把"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "料酒", Qty: 1, Unit: "适量"},
			{Name: "淀粉", Qty: 1, Unit: "适量"},
			{Name: "鸡蛋", Qty: 1, Unit: "个"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "红烧肉", Tag: "家常", Servings: 4,
		Steps: []string{"五花肉切 3cm 方块，冷水下锅焯去血沫", "锅中放冰糖炒出糖色", "下肉块翻炒均匀上色", "加姜、八角、桂皮、香叶、生抽老抽料酒", "加水没过肉，小火炖 40 分钟", "大火收汁至酱红发亮"},
		Items: []recItemDef{
			{Name: "五花肉", Qty: 500, Unit: "g"},
			{Name: "冰糖", Qty: 20, Unit: "g"},
			{Name: "姜", Qty: 15, Unit: "g"},
			{Name: "八角", Qty: 2, Unit: "个"},
			{Name: "桂皮", Qty: 1, Unit: "片"},
			{Name: "香叶", Qty: 2, Unit: "片"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "老抽", Qty: 1, Unit: "适量"},
			{Name: "料酒", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "宫保鸡丁", Tag: "川菜", Servings: 2,
		Steps: []string{"鸡胸切丁，盐、料酒、淀粉抓匀", "花生米过油炸至微黄", "调宫保汁：糖醋生抽淀粉", "热油爆干辣椒花椒", "下鸡丁滑散，倒汁翻匀", "最后下花生米迅速出锅"},
		Items: []recItemDef{
			{Name: "鸡胸肉", Qty: 250, Unit: "g"},
			{Name: "花生", Qty: 40, Unit: "g"},
			{Name: "干辣椒", Qty: 6, Unit: "个"},
			{Name: "花椒", Qty: 5, Unit: "g"},
			{Name: "葱", Qty: 2, Unit: "根"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "白糖", Qty: 1, Unit: "适量"},
			{Name: "醋", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "淀粉", Qty: 1, Unit: "适量"},
			{Name: "料酒", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "麻婆豆腐", Tag: "川菜", Servings: 2,
		Steps: []string{"豆腐切块，盐水焯一下定型", "猪肉末炒出油", "下豆瓣酱炒出红油", "加水与豆腐小火煨 3 分钟", "水淀粉勾薄芡", "撒花椒粉与蒜苗"},
		Items: []recItemDef{
			{Name: "豆腐", Qty: 400, Unit: "g"},
			{Name: "猪肉", Qty: 80, Unit: "g"},
			{Name: "郫县豆瓣酱", Qty: 20, Unit: "g"},
			{Name: "花椒", Qty: 5, Unit: "g"},
			{Name: "蒜苗", Qty: 30, Unit: "g", Opt: true},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "淀粉", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "鱼香肉丝", Tag: "川菜", Servings: 2,
		Steps: []string{"猪肉切丝上浆", "胡萝卜、木耳、青椒切丝", "调鱼香汁：糖醋生抽豆瓣", "肉丝滑油盛出", "爆香姜蒜，下配菜", "倒回肉丝与汁，翻匀出锅"},
		Items: []recItemDef{
			{Name: "猪肉", Qty: 200, Unit: "g"},
			{Name: "胡萝卜", Qty: 50, Unit: "g"},
			{Name: "木耳", Qty: 20, Unit: "g"},
			{Name: "青椒", Qty: 1, Unit: "个"},
			{Name: "郫县豆瓣酱", Qty: 15, Unit: "g"},
			{Name: "姜", Qty: 8, Unit: "g"},
			{Name: "蒜", Qty: 3, Unit: "瓣"},
			{Name: "白糖", Qty: 1, Unit: "适量"},
			{Name: "醋", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "淀粉", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "糖醋排骨", Tag: "家常", Servings: 3,
		Steps: []string{"排骨斩段焯水", "热油煎至表面金黄", "加糖、醋、生抽、料酒", "加水没过排骨小火 25 分钟", "大火收汁至亮红裹匀"},
		Items: []recItemDef{
			{Name: "猪排骨", Qty: 500, Unit: "g"},
			{Name: "白糖", Qty: 1, Unit: "适量"},
			{Name: "醋", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "料酒", Qty: 1, Unit: "适量"},
			{Name: "姜", Qty: 10, Unit: "g"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "青椒土豆丝", Tag: "家常", Servings: 2,
		Steps: []string{"土豆切细丝，清水漂去淀粉", "青椒切丝", "热油爆花椒出香捞出", "下土豆丝大火快炒", "加青椒、盐、醋、少许糖迅速出锅"},
		Items: []recItemDef{
			{Name: "土豆", Qty: 300, Unit: "g"},
			{Name: "青椒", Qty: 2, Unit: "个"},
			{Name: "花椒", Qty: 3, Unit: "g"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "醋", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "蒜蓉菠菜", Tag: "家常", Servings: 2,
		Steps: []string{"菠菜洗净，开水焯 20 秒过凉", "蒜拍碎切末", "热油爆蒜蓉至金黄", "下菠菜大火翻炒", "加盐生抽出锅"},
		Items: []recItemDef{
			{Name: "菠菜", Qty: 300, Unit: "g"},
			{Name: "蒜", Qty: 4, Unit: "瓣"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "蛋炒饭", Tag: "家常", Servings: 1,
		Steps: []string{"隔夜米饭搓散", "鸡蛋打散", "热锅滑蛋盛出", "下米饭炒至粒粒分明", "倒回鸡蛋，加盐生抽葱花"},
		Items: []recItemDef{
			{Name: "大米", Qty: 150, Unit: "g"},
			{Name: "鸡蛋", Qty: 2, Unit: "个"},
			{Name: "葱", Qty: 1, Unit: "根"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "可乐鸡翅", Tag: "家常", Servings: 2,
		Steps: []string{"鸡翅两面划刀，焯水", "煎至两面金黄", "倒入可乐没过鸡翅", "加生抽老抽姜片", "中小火焖 15 分钟", "大火收汁至浓稠发亮"},
		Items: []recItemDef{
			{Name: "鸡翅", Qty: 8, Unit: "个"},
			{Name: "可乐", Qty: 330, Unit: "ml"},
			{Name: "姜", Qty: 10, Unit: "g"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "老抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "水煮牛肉", Tag: "川菜", Servings: 3,
		Steps: []string{"牛肉切片上浆", "生菜垫底焯熟", "豆瓣酱炒红油，加水烧开", "下牛肉片刚变色捞出铺在菜上", "撒干辣椒花椒，浇热油"},
		Items: []recItemDef{
			{Name: "牛肉", Qty: 300, Unit: "g"},
			{Name: "生菜", Qty: 200, Unit: "g"},
			{Name: "郫县豆瓣酱", Qty: 25, Unit: "g"},
			{Name: "干辣椒", Qty: 10, Unit: "个"},
			{Name: "花椒", Qty: 8, Unit: "g"},
			{Name: "蒜", Qty: 4, Unit: "瓣"},
			{Name: "淀粉", Qty: 1, Unit: "适量"},
			{Name: "料酒", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "番茄牛腩", Tag: "家常", Servings: 3,
		Steps: []string{"牛腩切块焯水", "西红柿去皮切块", "牛腩炒香后加水炖 60 分钟", "下西红柿继续炖 20 分钟", "加盐糖调味至汤汁浓郁"},
		Items: []recItemDef{
			{Name: "牛腩", Qty: 500, Unit: "g"},
			{Name: "西红柿", Qty: 3, Unit: "个"},
			{Name: "洋葱", Qty: 1, Unit: "个"},
			{Name: "姜", Qty: 15, Unit: "g"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "白糖", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "料酒", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "清蒸鲈鱼", Tag: "粤菜", Servings: 2,
		Steps: []string{"鲈鱼清理干净，两面斜刀", "姜丝铺底，鱼身放葱姜", "水开后上锅蒸 8 分钟", "倒掉蒸出的腥水", "铺葱丝浇热油，淋蒸鱼豉油"},
		Items: []recItemDef{
			{Name: "鲈鱼", Qty: 1, Unit: "条"},
			{Name: "姜", Qty: 15, Unit: "g"},
			{Name: "葱", Qty: 3, Unit: "根"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
			{Name: "料酒", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "蒜蓉虾", Tag: "粤菜", Servings: 2,
		Steps: []string{"虾剪须开背去线", "蒜剁蓉，一半油酥一半生蒜", "虾两面煎至变红", "下蒜蓉翻炒均匀", "加盐生抽出锅撒葱花"},
		Items: []recItemDef{
			{Name: "基围虾", Qty: 400, Unit: "g"},
			{Name: "蒜", Qty: 8, Unit: "瓣"},
			{Name: "葱", Qty: 1, Unit: "根"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "回锅肉", Tag: "川菜", Servings: 2,
		Steps: []string{"五花肉整块煮至筷子能扎入", "晾凉切薄片", "青椒蒜苗切段", "肉片煸至卷曲出油", "下豆瓣酱炒红油", "下配菜翻匀出锅"},
		Items: []recItemDef{
			{Name: "五花肉", Qty: 300, Unit: "g"},
			{Name: "青椒", Qty: 2, Unit: "个"},
			{Name: "蒜苗", Qty: 50, Unit: "g"},
			{Name: "郫县豆瓣酱", Qty: 20, Unit: "g"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "蚂蚁上树", Tag: "川菜", Servings: 2,
		Steps: []string{"粉丝温水泡软", "猪肉末炒香", "下豆瓣酱炒红油", "加水与生抽烧开", "下粉丝吸干汤汁", "撒葱花出锅"},
		Items: []recItemDef{
			{Name: "粉丝", Qty: 80, Unit: "g"},
			{Name: "猪肉", Qty: 80, Unit: "g"},
			{Name: "郫县豆瓣酱", Qty: 15, Unit: "g"},
			{Name: "葱", Qty: 1, Unit: "根"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "酸辣土豆丝", Tag: "家常", Servings: 2,
		Steps: []string{"土豆切极细丝漂水", "干辣椒剪段", "热油爆辣椒花椒", "下土豆丝大火翻炒", "加醋盐出锅，保持脆爽"},
		Items: []recItemDef{
			{Name: "土豆", Qty: 300, Unit: "g"},
			{Name: "干辣椒", Qty: 4, Unit: "个"},
			{Name: "花椒", Qty: 3, Unit: "g"},
			{Name: "醋", Qty: 1, Unit: "适量"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "木须肉", Tag: "家常", Servings: 2,
		Steps: []string{"猪肉切丝上浆", "鸡蛋摊成蛋皮切丝", "木耳黄瓜切丝", "肉丝滑油", "下配菜与蛋丝，加盐生抽翻匀"},
		Items: []recItemDef{
			{Name: "猪肉", Qty: 150, Unit: "g"},
			{Name: "鸡蛋", Qty: 2, Unit: "个"},
			{Name: "木耳", Qty: 20, Unit: "g"},
			{Name: "黄瓜", Qty: 1, Unit: "根"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "淀粉", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "西湖醋鱼", Tag: "浙菜", Servings: 2,
		Steps: []string{"草鱼剖开摊平", "清水加姜片煮 5 分钟至刚熟", "另起锅调糖醋汁勾芡", "浇在鱼身上即可"},
		Items: []recItemDef{
			{Name: "草鱼", Qty: 600, Unit: "g"},
			{Name: "姜", Qty: 10, Unit: "g"},
			{Name: "醋", Qty: 1, Unit: "适量"},
			{Name: "白糖", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "淀粉", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "香菇青菜", Tag: "家常", Servings: 2,
		Steps: []string{"香菇泡发切片", "青菜洗净", "热油炒香菇至出水", "下青菜大火翻炒", "加盐蚝油出锅"},
		Items: []recItemDef{
			{Name: "香菇", Qty: 80, Unit: "g"},
			{Name: "青菜", Qty: 300, Unit: "g"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "蚝油", Qty: 10, Unit: "ml"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "蛋花汤", Tag: "家常", Servings: 2,
		Steps: []string{"清水烧开加盐", "鸡蛋打散成细流倒入", "轻轻推动成蛋花", "淋芝麻油撒葱花紫菜"},
		Items: []recItemDef{
			{Name: "鸡蛋", Qty: 2, Unit: "个"},
			{Name: "紫菜", Qty: 5, Unit: "g"},
			{Name: "葱", Qty: 1, Unit: "根"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "芝麻油", Qty: 5, Unit: "ml"},
		},
	},
	{
		Name: "葱油拌面", Tag: "家常", Servings: 1,
		Steps: []string{"挂面煮至断生过凉", "小葱切段，热油炸至焦香成葱油", "面条加生抽、盐、葱油拌匀"},
		Items: []recItemDef{
			{Name: "挂面", Qty: 120, Unit: "g"},
			{Name: "葱", Qty: 4, Unit: "根"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "扬州炒饭", Tag: "家常", Servings: 2,
		Steps: []string{"米饭搓散", "火腿或猪肉、胡萝卜、豌豆切丁", "鸡蛋炒散", "下米饭与配菜炒匀", "加盐生抽出锅"},
		Items: []recItemDef{
			{Name: "大米", Qty: 250, Unit: "g"},
			{Name: "鸡蛋", Qty: 2, Unit: "个"},
			{Name: "猪肉", Qty: 50, Unit: "g"},
			{Name: "胡萝卜", Qty: 40, Unit: "g"},
			{Name: "豌豆", Qty: 40, Unit: "g"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "干煸四季豆", Tag: "川菜", Servings: 2,
		Steps: []string{"四季豆撕筋掰段", "中油温煸至表皮起皱盛出", "肉末炒香下豆瓣干辣椒", "倒回四季豆，加盐生抽翻匀"},
		Items: []recItemDef{
			{Name: "四季豆", Qty: 350, Unit: "g"},
			{Name: "猪肉", Qty: 60, Unit: "g"},
			{Name: "郫县豆瓣酱", Qty: 15, Unit: "g"},
			{Name: "干辣椒", Qty: 4, Unit: "个"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "白切鸡", Tag: "粤菜", Servings: 4,
		Steps: []string{"整鸡冷水下锅，加姜葱料酒", "水开转小火煮 20 分钟关火焖 15 分钟", "过冰水使皮爽", "斩件，蘸姜葱蓉"},
		Items: []recItemDef{
			{Name: "整鸡", Qty: 1, Unit: "只"},
			{Name: "姜", Qty: 20, Unit: "g"},
			{Name: "葱", Qty: 3, Unit: "根"},
			{Name: "料酒", Qty: 1, Unit: "适量"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "芝麻油", Qty: 10, Unit: "ml"},
		},
	},
	{
		Name: "红烧茄子", Tag: "家常", Servings: 2,
		Steps: []string{"茄子切滚刀块，盐水抓一下", "热油煎至软塌", "下蒜末豆瓣酱炒香", "加生抽糖少许水焖 3 分钟", "水淀粉勾芡"},
		Items: []recItemDef{
			{Name: "茄子", Qty: 2, Unit: "个"},
			{Name: "蒜", Qty: 4, Unit: "瓣"},
			{Name: "郫县豆瓣酱", Qty: 10, Unit: "g"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "白糖", Qty: 1, Unit: "适量"},
			{Name: "淀粉", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "醋溜白菜", Tag: "家常", Servings: 2,
		Steps: []string{"白菜手撕成块", "干辣椒姜丝爆香", "下白菜大火快炒", "加醋糖盐迅速出锅保持脆嫩"},
		Items: []recItemDef{
			{Name: "白菜", Qty: 400, Unit: "g"},
			{Name: "干辣椒", Qty: 3, Unit: "个"},
			{Name: "姜", Qty: 8, Unit: "g"},
			{Name: "醋", Qty: 1, Unit: "适量"},
			{Name: "白糖", Qty: 1, Unit: "适量"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "虾仁炒蛋", Tag: "家常", Servings: 2,
		Steps: []string{"虾仁去线，盐淀粉抓匀", "鸡蛋打散加少许盐", "虾仁滑油盛出", "蛋液炒至半凝固下虾仁", "翻匀出锅"},
		Items: []recItemDef{
			{Name: "虾", Qty: 200, Unit: "g"},
			{Name: "鸡蛋", Qty: 3, Unit: "个"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "淀粉", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
			{Name: "葱", Qty: 1, Unit: "根", Opt: true},
		},
	},
	{
		Name: "酸汤肥牛", Tag: "家常", Servings: 2,
		Steps: []string{"番茄切块炒出汁加水", "加泡椒、醋、盐调酸汤", "生菜垫碗", "肥牛涮至变色捞入碗", "浇热汤撒香菜"},
		Items: []recItemDef{
			{Name: "肥牛", Qty: 250, Unit: "g"},
			{Name: "西红柿", Qty: 2, Unit: "个"},
			{Name: "生菜", Qty: 150, Unit: "g"},
			{Name: "泡椒", Qty: 20, Unit: "g"},
			{Name: "香菜", Qty: 1, Unit: "把"},
			{Name: "醋", Qty: 1, Unit: "适量"},
			{Name: "盐", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "小炒黄牛肉", Tag: "湘菜", Servings: 2,
		Steps: []string{"牛肉切薄片重油上浆", "芹菜青椒切段", "牛肉大火滑散盛出", "下配菜爆香", "倒回牛肉加生抽蚝油迅速出锅"},
		Items: []recItemDef{
			{Name: "牛肉", Qty: 250, Unit: "g"},
			{Name: "芹菜", Qty: 80, Unit: "g"},
			{Name: "青椒", Qty: 2, Unit: "个"},
			{Name: "蒜", Qty: 3, Unit: "瓣"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "蚝油", Qty: 8, Unit: "ml"},
			{Name: "淀粉", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "紫菜蛋花汤", Tag: "家常", Servings: 2,
		Steps: []string{"紫菜撕小片", "水开下紫菜虾皮", "倒入蛋液成花", "加盐芝麻油出锅"},
		Items: []recItemDef{
			{Name: "紫菜", Qty: 8, Unit: "g"},
			{Name: "鸡蛋", Qty: 2, Unit: "个"},
			{Name: "虾皮", Qty: 8, Unit: "g"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "芝麻油", Qty: 5, Unit: "ml"},
		},
	},
	{
		Name: "咖喱鸡块", Tag: "家常", Servings: 3,
		Steps: []string{"鸡腿切块焯水", "土豆胡萝卜洋葱切块", "鸡块煎至上色", "下咖喱块与椰浆加水焖 20 分钟", "至土豆软烂汤汁浓稠"},
		Items: []recItemDef{
			{Name: "鸡腿", Qty: 4, Unit: "个"},
			{Name: "土豆", Qty: 250, Unit: "g"},
			{Name: "胡萝卜", Qty: 100, Unit: "g"},
			{Name: "洋葱", Qty: 1, Unit: "个"},
			{Name: "咖喱块", Qty: 2, Unit: "块"},
			{Name: "椰浆", Qty: 100, Unit: "ml"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "清炒时蔬", Tag: "家常", Servings: 2,
		Steps: []string{"油麦菜撕段洗净", "蒜末爆香", "大火快炒至断生", "加盐蚝油出锅"},
		Items: []recItemDef{
			{Name: "油麦菜", Qty: 300, Unit: "g"},
			{Name: "蒜", Qty: 3, Unit: "瓣"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "蚝油", Qty: 8, Unit: "ml"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "蒜泥黄瓜", Tag: "凉菜", Servings: 2,
		Steps: []string{"黄瓜拍裂切段", "蒜捣泥", "加盐糖醋生抽芝麻油拌匀冷藏 10 分钟"},
		Items: []recItemDef{
			{Name: "黄瓜", Qty: 2, Unit: "根"},
			{Name: "蒜", Qty: 4, Unit: "瓣"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "白糖", Qty: 1, Unit: "适量"},
			{Name: "醋", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "芝麻油", Qty: 5, Unit: "ml"},
		},
	},
	{
		Name: "香煎鳕鱼", Tag: "西式", Servings: 2,
		Steps: []string{"鳕鱼拭干，盐胡椒腌 10 分钟", "热锅黄油煎至两面金黄", "挤少许柠檬意（可用醋代替）出锅"},
		Items: []recItemDef{
			{Name: "鳕鱼", Qty: 300, Unit: "g"},
			{Name: "黄油", Qty: 15, Unit: "g"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "胡椒粉", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "味噌汤", Tag: "日式", Servings: 2,
		Steps: []string{"海带加水小火煮出鲜味捞出", "豆腐切丁下锅", "味噌用汤汁化开再倒回，勿沸", "撒葱花"},
		Items: []recItemDef{
			{Name: "味噌", Qty: 20, Unit: "g"},
			{Name: "豆腐", Qty: 150, Unit: "g"},
			{Name: "海带", Qty: 10, Unit: "g"},
			{Name: "葱", Qty: 1, Unit: "根"},
		},
	},
	{
		Name: "蚝油杏鲍菇", Tag: "家常", Servings: 2,
		Steps: []string{"杏鲍菇切条", "热油煎至表面焦香", "下蒜末蚝油少许水焖 2 分钟", "大火收汁"},
		Items: []recItemDef{
			{Name: "杏鲍菇", Qty: 250, Unit: "g"},
			{Name: "蒜", Qty: 3, Unit: "瓣"},
			{Name: "蚝油", Qty: 12, Unit: "ml"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "蒜蓉金针菇", Tag: "家常", Servings: 2,
		Steps: []string{"金针菇去根洗净", "摆盘撒满蒜蓉", "淋生抽蚝油", "上锅蒸 6 分钟", "浇热油出锅"},
		Items: []recItemDef{
			{Name: "金针菇", Qty: 250, Unit: "g"},
			{Name: "蒜", Qty: 6, Unit: "瓣"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "蚝油", Qty: 8, Unit: "ml"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "清炒豆芽", Tag: "家常", Servings: 2,
		Steps: []string{"豆芽洗净控水", "热锅少油大火", "下豆芽快炒至断生", "加盐醋出锅保持爽脆"},
		Items: []recItemDef{
			{Name: "豆芽", Qty: 300, Unit: "g"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "醋", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
			{Name: "辣椒", Qty: 1, Unit: "个", Opt: true},
		},
	},
	{
		Name: "红烧鸡腿", Tag: "家常", Servings: 2,
		Steps: []string{"鸡腿两面划刀焯水", "煎至表皮金黄", "加生抽老抽料酒冰糖", "加水焖 20 分钟", "收汁至酱色发亮"},
		Items: []recItemDef{
			{Name: "鸡腿", Qty: 4, Unit: "个"},
			{Name: "姜", Qty: 10, Unit: "g"},
			{Name: "冰糖", Qty: 15, Unit: "g"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "老抽", Qty: 1, Unit: "适量"},
			{Name: "料酒", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "蒜蓉粉丝蒸虾", Tag: "粤菜", Servings: 2,
		Steps: []string{"粉丝泡软垫底", "虾开背摆在粉丝上", "蒜蓉加生抽蚝油拌匀铺上", "蒸 6 分钟浇热油"},
		Items: []recItemDef{
			{Name: "基围虾", Qty: 350, Unit: "g"},
			{Name: "粉丝", Qty: 60, Unit: "g"},
			{Name: "蒜", Qty: 8, Unit: "瓣"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "蚝油", Qty: 8, Unit: "ml"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "上汤娃娃菜", Tag: "家常", Servings: 2,
		Steps: []string{"小白菜对半切开", "热油煎切面至微黄", "加高汤意（水+蚝油）焖 3 分钟", "水淀粉薄芡"},
		Items: []recItemDef{
			{Name: "小白菜", Qty: 300, Unit: "g"},
			{Name: "蚝油", Qty: 10, Unit: "ml"},
			{Name: "蒜", Qty: 2, Unit: "瓣"},
			{Name: "淀粉", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
			{Name: "盐", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "干锅花菜意", Tag: "湘菜", Servings: 2,
		Steps: []string{"用西葫芦代替花菜切片干煸", "下猪肉末与干辣椒", "加生抽蚝油翻匀出锅"},
		Items: []recItemDef{
			{Name: "西葫芦", Qty: 1, Unit: "个"},
			{Name: "猪肉", Qty: 60, Unit: "g"},
			{Name: "干辣椒", Qty: 5, Unit: "个"},
			{Name: "蒜", Qty: 3, Unit: "瓣"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "蚝油", Qty: 8, Unit: "ml"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "白灼西兰花", Tag: "粤菜", Servings: 2,
		Steps: []string{"西兰花掰小朵盐水焯 1 分钟", "过凉沥干", "蒜蓉生抽蚝油淋上", "浇热油"},
		Items: []recItemDef{
			{Name: "西兰花", Qty: 300, Unit: "g"},
			{Name: "蒜", Qty: 3, Unit: "瓣"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "蚝油", Qty: 8, Unit: "ml"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "干锅菜花", Tag: "湘菜", Servings: 2,
		Steps: []string{"菜花掰小朵焯水", "控干后干煸至焦边", "下猪肉末干辣椒", "加生抽蚝油翻匀"},
		Items: []recItemDef{
			{Name: "菜花", Qty: 350, Unit: "g"},
			{Name: "猪肉", Qty: 60, Unit: "g"},
			{Name: "干辣椒", Qty: 5, Unit: "个"},
			{Name: "蒜", Qty: 3, Unit: "瓣"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "蚝油", Qty: 8, Unit: "ml"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "蚝油生菜", Tag: "粤菜", Servings: 2,
		Steps: []string{"生菜整棵洗净", "开水焯至翠绿过凉", "调蚝油汁浇上"},
		Items: []recItemDef{
			{Name: "生菜", Qty: 250, Unit: "g"},
			{Name: "蚝油", Qty: 15, Unit: "ml"},
			{Name: "蒜", Qty: 2, Unit: "瓣"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "清炒芦笋", Tag: "家常", Servings: 2,
		Steps: []string{"芦笋去老根斜切", "热油蒜末爆香", "大火快炒加盐出锅"},
		Items: []recItemDef{
			{Name: "芦笋", Qty: 250, Unit: "g"},
			{Name: "蒜", Qty: 3, Unit: "瓣"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "豆皮青菜", Tag: "家常", Servings: 2,
		Steps: []string{"豆皮切丝", "青菜切段", "热油先炒豆皮", "下青菜加盐生抽"},
		Items: []recItemDef{
			{Name: "豆皮", Qty: 80, Unit: "g"},
			{Name: "青菜", Qty: 250, Unit: "g"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "秋葵拌蒜", Tag: "凉菜", Servings: 2,
		Steps: []string{"秋葵焯水过凉", "蒜泥加盐生抽芝麻油", "拌匀即可"},
		Items: []recItemDef{
			{Name: "秋葵", Qty: 200, Unit: "g"},
			{Name: "蒜", Qty: 4, Unit: "瓣"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "芝麻油", Qty: 5, Unit: "ml"},
		},
	},
	{
		Name: "清炒莴笋丝", Tag: "家常", Servings: 2,
		Steps: []string{"莴笋去皮切丝", "热油蒜末", "下莴笋大火翻炒", "加盐出锅"},
		Items: []recItemDef{
			{Name: "莴笋", Qty: 300, Unit: "g"},
			{Name: "蒜", Qty: 3, Unit: "瓣"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "葱油鸡爪", Tag: "凉菜", Servings: 2,
		Steps: []string{"鸡爪斩小块焯水", "加姜葱煮 15 分钟", "过凉浇葱油生抽"},
		Items: []recItemDef{
			{Name: "鸡爪", Qty: 400, Unit: "g"},
			{Name: "葱", Qty: 3, Unit: "根"},
			{Name: "姜", Qty: 10, Unit: "g"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "黄豆焖猪蹄", Tag: "家常", Servings: 4,
		Steps: []string{"猪蹄斩块焯水", "炒糖色上色", "加生抽老抽料酒", "小火焖 60 分钟至软烂"},
		Items: []recItemDef{
			{Name: "猪蹄", Qty: 2, Unit: "个"},
			{Name: "姜", Qty: 15, Unit: "g"},
			{Name: "八角", Qty: 2, Unit: "个"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "老抽", Qty: 1, Unit: "适量"},
			{Name: "料酒", Qty: 1, Unit: "适量"},
			{Name: "冰糖", Qty: 15, Unit: "g"},
		},
	},
	{
		Name: "蒜蓉生蚝", Tag: "粤菜", Servings: 2,
		Steps: []string{"牡蛎开壳摆盘", "铺蒜蓉粉丝", "蒸 5 分钟浇热油生抽"},
		Items: []recItemDef{
			{Name: "牡蛎", Qty: 8, Unit: "个"},
			{Name: "粉丝", Qty: 40, Unit: "g"},
			{Name: "蒜", Qty: 8, Unit: "瓣"},
			{Name: "生抽", Qty: 1, Unit: "适量"},
			{Name: "辣椒", Qty: 1, Unit: "个", Opt: true},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "香煎带鱼", Tag: "家常", Servings: 2,
		Steps: []string{"带鱼段抹盐料酒腌 15 分钟", "拍薄淀粉", "热油煎至两面焦黄"},
		Items: []recItemDef{
			{Name: "带鱼段", Qty: 350, Unit: "g"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "料酒", Qty: 1, Unit: "适量"},
			{Name: "淀粉", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "番茄鸡蛋汤", Tag: "家常", Servings: 2,
		Steps: []string{"西红柿切块炒出汁", "加水烧开", "倒入蛋液成花", "加盐葱花"},
		Items: []recItemDef{
			{Name: "西红柿", Qty: 2, Unit: "个"},
			{Name: "鸡蛋", Qty: 2, Unit: "个"},
			{Name: "葱", Qty: 1, Unit: "根"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "芝麻油", Qty: 5, Unit: "ml"},
		},
	},
	{
		Name: "椒盐蘑菇", Tag: "家常", Servings: 2,
		Steps: []string{"平菇撕条拍干", "热油煎至焦边", "撒椒盐蒜末出锅"},
		Items: []recItemDef{
			{Name: "平菇", Qty: 250, Unit: "g"},
			{Name: "蒜", Qty: 3, Unit: "瓣"},
			{Name: "盐", Qty: 1, Unit: "适量"},
			{Name: "胡椒粉", Qty: 1, Unit: "适量"},
			{Name: "食用油", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "海带排骨汤", Tag: "家常", Servings: 3,
		Steps: []string{"海带泡发切结", "排骨焯水", "加水小火炖 40 分钟", "加盐出锅"},
		Items: []recItemDef{
			{Name: "猪排骨", Qty: 400, Unit: "g"},
			{Name: "海带", Qty: 80, Unit: "g"},
			{Name: "姜", Qty: 10, Unit: "g"},
			{Name: "盐", Qty: 1, Unit: "适量"},
		},
	},
	{
		Name: "红枣枸杞汤", Tag: "家常", Servings: 2,
		Steps: []string{"红枣枸杞洗净", "加水煮 15 分钟", "可加冰糖"},
		Items: []recItemDef{
			{Name: "红枣", Qty: 8, Unit: "个"},
			{Name: "枸杞", Qty: 10, Unit: "g"},
			{Name: "冰糖", Qty: 10, Unit: "g", Opt: true},
		},
	},
	{
		Name: "奶香吐司意", Tag: "早餐", Servings: 1,
		Steps: []string{"无面包时用牛奶鸡蛋做滑蛋", "配酸奶"},
		Items: []recItemDef{
			{Name: "鸡蛋", Qty: 2, Unit: "个"},
			{Name: "牛奶", Qty: 50, Unit: "ml"},
			{Name: "酸奶", Qty: 1, Unit: "杯"},
			{Name: "黄油", Qty: 8, Unit: "g"},
		},
	},
}
