package db

import "gocooking/internal/model"

// 食材目录约定：
//   - Name 是聚合主键文案；Aliases 必须能反查到同一 ID（番茄→西红柿）
//   - Dim 与 DefaultUnit 一致：斤/g 用 weight，把/根 用 unknown
//   - Staple=true 仅给 9 项默认常备：盐、生抽、老抽、食用油、白糖、料酒、醋、淀粉、胡椒粉
//   - Stall 覆盖蔬菜摊/肉摊/水产摊/干货调料摊/蛋奶摊，缺一不可

// ingredientCatalog 内置 ≥120 项，覆盖全部摊位与蔬菜细分类。
// 别名必须能归一：番茄/西红柿/洋柿子 → 同一食材。
var ingredientCatalog = []ingDef{
	{Name: "白菜", Aliases: []string{"大白菜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "青菜", Aliases: []string{"上海青", "小青菜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "菠菜", Aliases: []string{"赤根菜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "生菜", Aliases: []string{"圆生菜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "油麦菜", Aliases: []string{"莜麦菜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "韭菜", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "芹菜", Aliases: []string{"西芹"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "香菜", Aliases: []string{"芫荽", "胡荽"}, Unit: "把", Dim: model.DimUnknown, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "茼蒿", Aliases: []string{"蓬蒿"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "空心菜", Aliases: []string{"蕹菜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "芥蓝", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "小白菜", Aliases: []string{"青白菜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "生菜叶", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "菜心", Aliases: []string{"菜薹"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},

	{Name: "土豆", Aliases: []string{"马铃薯", "洋芋"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatRoot, Stall: model.StallVeg},
	{Name: "胡萝卜", Aliases: []string{"红萝卜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatRoot, Stall: model.StallVeg},
	{Name: "白萝卜", Aliases: []string{"萝卜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatRoot, Stall: model.StallVeg},
	{Name: "红薯", Aliases: []string{"地瓜", "番薯"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatRoot, Stall: model.StallVeg},
	{Name: "莲藕", Aliases: []string{"藕"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatRoot, Stall: model.StallVeg},
	{Name: "山药", Aliases: []string{"淮山"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatRoot, Stall: model.StallVeg},
	{Name: "芋头", Aliases: []string{"芋艿"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatRoot, Stall: model.StallVeg},
	{Name: "姜", Aliases: []string{"生姜", "黄姜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatRoot, Stall: model.StallVeg},
	{Name: "蒜", Aliases: []string{"大蒜", "蒜头"}, Unit: "瓣", Dim: model.DimUnknown, Cat: model.CatRoot, Stall: model.StallVeg},
	{Name: "洋葱", Aliases: []string{"葱头"}, Unit: "个", Dim: model.DimCount, Cat: model.CatRoot, Stall: model.StallVeg},
	{Name: "葱", Aliases: []string{"小葱", "香葱"}, Unit: "根", Dim: model.DimUnknown, Cat: model.CatRoot, Stall: model.StallVeg},
	{Name: "蒜苗", Aliases: []string{"青蒜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatRoot, Stall: model.StallVeg},

	{Name: "西红柿", Aliases: []string{"番茄", "洋柿子"}, Unit: "个", Dim: model.DimCount, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "黄瓜", Aliases: []string{"青瓜"}, Unit: "根", Dim: model.DimUnknown, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "茄子", Aliases: []string{"紫茄"}, Unit: "个", Dim: model.DimCount, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "青椒", Aliases: []string{"柿子椒", "甜椒"}, Unit: "个", Dim: model.DimCount, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "辣椒", Aliases: []string{"尖椒", "小米椒"}, Unit: "个", Dim: model.DimCount, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "南瓜", Aliases: []string{"倭瓜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "冬瓜", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "丝瓜", Aliases: []string{}, Unit: "根", Dim: model.DimUnknown, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "苦瓜", Aliases: []string{}, Unit: "根", Dim: model.DimUnknown, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "西葫芦", Aliases: []string{"角瓜"}, Unit: "个", Dim: model.DimCount, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "玉米", Aliases: []string{"苞谷"}, Unit: "根", Dim: model.DimUnknown, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "豌豆", Aliases: []string{"青豆"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "荷兰豆", Aliases: []string{"甜豆"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMelon, Stall: model.StallVeg},

	{Name: "香菇", Aliases: []string{"冬菇"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMushroom, Stall: model.StallVeg},
	{Name: "金针菇", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMushroom, Stall: model.StallVeg},
	{Name: "杏鲍菇", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMushroom, Stall: model.StallVeg},
	{Name: "平菇", Aliases: []string{"蚝菇"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMushroom, Stall: model.StallVeg},
	{Name: "木耳", Aliases: []string{"黑木耳"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMushroom, Stall: model.StallVeg},
	{Name: "银耳", Aliases: []string{"白木耳"}, Unit: "朵", Dim: model.DimUnknown, Cat: model.CatMushroom, Stall: model.StallVeg},
	{Name: "口蘑", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMushroom, Stall: model.StallVeg},

	{Name: "豆腐", Aliases: []string{"嫩豆腐", "老豆腐"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatBean, Stall: model.StallVeg},
	{Name: "豆干", Aliases: []string{"豆腐干"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatBean, Stall: model.StallVeg},
	{Name: "腐竹", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatBean, Stall: model.StallVeg},
	{Name: "豆芽", Aliases: []string{"黄豆芽", "绿豆芽"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatBean, Stall: model.StallVeg},
	{Name: "毛豆", Aliases: []string{"青大豆"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatBean, Stall: model.StallVeg},
	{Name: "四季豆", Aliases: []string{"刀豆", "芸豆"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatBean, Stall: model.StallVeg},

	{Name: "猪肉", Aliases: []string{"猪瘦肉", "前腿肉"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "猪排骨", Aliases: []string{"排骨"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "五花肉", Aliases: []string{"三层肉"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "猪里脊", Aliases: []string{"里脊"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "牛肉", Aliases: []string{"黄牛肉"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "牛腩", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "羊肉", Aliases: []string{"羊腿肉"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "鸡腿", Aliases: []string{"琵琶腿"}, Unit: "个", Dim: model.DimCount, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "鸡胸肉", Aliases: []string{"鸡胸"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "整鸡", Aliases: []string{"土鸡"}, Unit: "只", Dim: model.DimCount, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "鸡翅", Aliases: []string{"翅中"}, Unit: "个", Dim: model.DimCount, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "鸭肉", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "培根", Aliases: []string{}, Unit: "片", Dim: model.DimUnknown, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "肥牛", Aliases: []string{"肥牛卷"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMeat, Stall: model.StallMeat},

	{Name: "草鱼", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatAqua, Stall: model.StallAqua},
	{Name: "鲈鱼", Aliases: []string{"海鲈"}, Unit: "条", Dim: model.DimUnknown, Cat: model.CatAqua, Stall: model.StallAqua},
	{Name: "带鱼", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatAqua, Stall: model.StallAqua},
	{Name: "黄鱼", Aliases: []string{"小黄鱼"}, Unit: "条", Dim: model.DimUnknown, Cat: model.CatAqua, Stall: model.StallAqua},
	{Name: "虾", Aliases: []string{"青虾"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatAqua, Stall: model.StallAqua},
	{Name: "基围虾", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatAqua, Stall: model.StallAqua},
	{Name: "螃蟹", Aliases: []string{"大闸蟹"}, Unit: "只", Dim: model.DimCount, Cat: model.CatAqua, Stall: model.StallAqua},
	{Name: "蛤蜊", Aliases: []string{"花蛤"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatAqua, Stall: model.StallAqua},
	{Name: "鱿鱼", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatAqua, Stall: model.StallAqua},
	{Name: "鳕鱼", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatAqua, Stall: model.StallAqua},
	{Name: "三文鱼", Aliases: []string{"鲑鱼"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatAqua, Stall: model.StallAqua},
	{Name: "酸菜鱼片", Aliases: []string{"黑鱼片", "巴沙鱼"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatAqua, Stall: model.StallAqua},

	{Name: "鸡蛋", Aliases: []string{"鸡子", "蛋"}, Unit: "个", Dim: model.DimCount, Cat: model.CatEgg, Stall: model.StallDairy},
	{Name: "鸭蛋", Aliases: []string{}, Unit: "个", Dim: model.DimCount, Cat: model.CatEgg, Stall: model.StallDairy},
	{Name: "鹌鹑蛋", Aliases: []string{}, Unit: "个", Dim: model.DimCount, Cat: model.CatEgg, Stall: model.StallDairy},
	{Name: "牛奶", Aliases: []string{"鲜奶"}, Unit: "ml", Dim: model.DimVolume, Cat: model.CatEgg, Stall: model.StallDairy},
	{Name: "酸奶", Aliases: []string{}, Unit: "杯", Dim: model.DimUnknown, Cat: model.CatEgg, Stall: model.StallDairy},
	{Name: "黄油", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatEgg, Stall: model.StallDairy},
	{Name: "芝士", Aliases: []string{"奶酪"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatEgg, Stall: model.StallDairy},

	{Name: "盐", Aliases: []string{"食盐"}, Unit: "适量", Dim: model.DimDimensionless, Cat: model.CatSpice, Stall: model.StallSpice, Staple: true},
	{Name: "生抽", Aliases: []string{"酱油"}, Unit: "适量", Dim: model.DimDimensionless, Cat: model.CatSpice, Stall: model.StallSpice, Staple: true},
	{Name: "老抽", Aliases: []string{}, Unit: "适量", Dim: model.DimDimensionless, Cat: model.CatSpice, Stall: model.StallSpice, Staple: true},
	{Name: "食用油", Aliases: []string{"菜籽油", "花生油"}, Unit: "适量", Dim: model.DimDimensionless, Cat: model.CatSpice, Stall: model.StallSpice, Staple: true},
	{Name: "白糖", Aliases: []string{"砂糖"}, Unit: "适量", Dim: model.DimDimensionless, Cat: model.CatSpice, Stall: model.StallSpice, Staple: true},
	{Name: "料酒", Aliases: []string{"黄酒"}, Unit: "适量", Dim: model.DimDimensionless, Cat: model.CatSpice, Stall: model.StallSpice, Staple: true},
	{Name: "醋", Aliases: []string{"米醋", "香醋"}, Unit: "适量", Dim: model.DimDimensionless, Cat: model.CatSpice, Stall: model.StallSpice, Staple: true},
	{Name: "淀粉", Aliases: []string{"生粉", "玉米淀粉"}, Unit: "适量", Dim: model.DimDimensionless, Cat: model.CatSpice, Stall: model.StallSpice, Staple: true},
	{Name: "胡椒粉", Aliases: []string{"白胡椒粉"}, Unit: "适量", Dim: model.DimDimensionless, Cat: model.CatSpice, Stall: model.StallSpice, Staple: true},
	{Name: "花椒", Aliases: []string{"川椒"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "郫县豆瓣酱", Aliases: []string{"豆瓣酱"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "泡椒", Aliases: []string{"野山椒"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "芝麻油", Aliases: []string{"香油"}, Unit: "ml", Dim: model.DimVolume, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "蚝油", Aliases: []string{}, Unit: "ml", Dim: model.DimVolume, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "味精", Aliases: []string{}, Unit: "适量", Dim: model.DimDimensionless, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "鸡精", Aliases: []string{}, Unit: "适量", Dim: model.DimDimensionless, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "八角", Aliases: []string{"大料"}, Unit: "个", Dim: model.DimCount, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "桂皮", Aliases: []string{}, Unit: "片", Dim: model.DimUnknown, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "香叶", Aliases: []string{"月桂叶"}, Unit: "片", Dim: model.DimUnknown, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "干辣椒", Aliases: []string{"干红椒"}, Unit: "个", Dim: model.DimCount, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "孜然", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "芝麻", Aliases: []string{"白芝麻"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "番茄酱", Aliases: []string{"ketchup"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "沙拉酱", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "咖喱块", Aliases: []string{}, Unit: "块", Dim: model.DimUnknown, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "韩式辣椒酱", Aliases: []string{"辣白菜酱"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatSpice, Stall: model.StallSpice},
	{Name: "味噌", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatSpice, Stall: model.StallSpice},

	{Name: "花生", Aliases: []string{"花生米"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "粉丝", Aliases: []string{"粉条"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "挂面", Aliases: []string{"面条"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "大米", Aliases: []string{"米"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "糯米", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "面粉", Aliases: []string{"中筋面粉"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "面包糠", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "海带", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "紫菜", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "虾皮", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "枸杞", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "红枣", Aliases: []string{"枣"}, Unit: "个", Dim: model.DimCount, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "冰糖", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "蜂蜜", Aliases: []string{}, Unit: "ml", Dim: model.DimVolume, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "椰浆", Aliases: []string{}, Unit: "ml", Dim: model.DimVolume, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "酸菜", Aliases: []string{"泡菜", "酸青菜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "木耳干", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatDry, Stall: model.StallSpice},
	{Name: "可乐", Aliases: []string{}, Unit: "ml", Dim: model.DimVolume, Cat: model.CatOther, Stall: model.StallSpice},
	{Name: "西兰花", Aliases: []string{"绿花菜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "菜花", Aliases: []string{"花椰菜"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "秋葵", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMelon, Stall: model.StallVeg},
	{Name: "芦笋", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatLeaf, Stall: model.StallVeg},
	{Name: "莴笋", Aliases: []string{"莴苣"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatRoot, Stall: model.StallVeg},
	{Name: "豆皮", Aliases: []string{"豆腐皮"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatBean, Stall: model.StallVeg},
	{Name: "鸡爪", Aliases: []string{"凤爪"}, Unit: "g", Dim: model.DimWeight, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "猪蹄", Aliases: []string{}, Unit: "个", Dim: model.DimCount, Cat: model.CatMeat, Stall: model.StallMeat},
	{Name: "带鱼段", Aliases: []string{}, Unit: "g", Dim: model.DimWeight, Cat: model.CatAqua, Stall: model.StallAqua},
	{Name: "牡蛎", Aliases: []string{"生蚝"}, Unit: "个", Dim: model.DimCount, Cat: model.CatAqua, Stall: model.StallAqua},
}
